# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\UltraBlur\Desktop\Coding\UltraRawConverter\UI\URC-About.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_About(object):
    def setupUi(self, Dialog_About):
        Dialog_About.setObjectName("Dialog_About")
        Dialog_About.resize(501, 234)
        self.label = QtWidgets.QLabel(Dialog_About)
        self.label.setGeometry(QtCore.QRect(30, 50, 101, 91))
        self.label.setStyleSheet("border-image:url(:/Logos/logo.png)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_About)
        self.label_2.setGeometry(QtCore.QRect(130, 40, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 170, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_About)
        self.label_3.setGeometry(QtCore.QRect(360, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog_About)
        self.label_4.setGeometry(QtCore.QRect(200, 120, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog_About)
        self.label_5.setGeometry(QtCore.QRect(330, 150, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog_About)
        QtCore.QMetaObject.connectSlotsByName(Dialog_About)

    def retranslateUi(self, Dialog_About):
        _translate = QtCore.QCoreApplication.translate
        Dialog_About.setWindowTitle(_translate("Dialog_About", "Ultra Raw Converter About"))
        self.label_2.setText(_translate("Dialog_About", "Ultra Raw Converter"))
        self.label_3.setText(_translate("Dialog_About", "0.1.0-Beta"))
        self.label_4.setText(_translate("Dialog_About", "Mail: gaohuyuchen@gmail.com"))
        self.label_5.setText(_translate("Dialog_About", "Readme.md"))
import Pic.Pic_qrc_rc
